### ISSUE TITLE
Docker Postgres 9.4 failure

### ISSUE THREAD

**Issue by emkatz** [springbootbuch/database_examples#1]
Postgres 9.4.20 is up to date for 9.4 now but fails with an
org.postgresql.util.PSQLException: ERROR: role "postgres" does not exist
on mvn clean verify
-> Some older Version e.g. 9.4.10 runs well.

**Comment by schokominzpfefferlade** [comment]
> 
> 
> Postgres 9.4.20 is up to date for 9.4 now but fails with an
> org.postgresql.util.PSQLException: ERROR: role "postgres" does not exist
> on mvn clean verify
> -> Some older Version e.g. 9.4.10 runs well.

Has the same issue. Fixed it by adding CREATE ROLE postgres to 
src/main/resources/db/migration/V0001__Create_pagila_schema.sql.sql :

```
...
SET check_function_bodies = false;
SET client_min_messages = warning;
SET escape_string_warning = off;

**CREATE ROLE postgres;**

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS 'Standard public schema';
...
```
